apiVersion: v1
kind: ResourceQuota
metadata:
  name: helixterminator
  namespace: helixterminator
spec:
  hard:
    requests.cpu: "25"
    requests.memory: 6400Mi
    limits.cpu: "125"
    limits.memory: 12800Mi
    pods: "100"
    services: "50"
    persistentvolumeclaims: "0"
    secrets: "50"
    configmaps: "50"
