# syntax=docker/dockerfile:1
FROM golang:1.22-alpine
RUN go install github.com/cosmtrek/air@latest && \
    go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 8080 40000
CMD ["air", "-c", ".air.toml"]
