apiVersion: v1
kind: LimitRange
metadata:
  name: helixterminator
  namespace: helixterminator
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 100m
      max:
        memory: 2Gi
        cpu: 2000m
      min:
        memory: 128Mi
        cpu: 50m
      type: Container
    - max:
        storage: 100Gi
      min:
        storage: 1Gi
      type: PersistentVolumeClaim
