apiVersion: v1
kind: ResourceQuota
metadata:
  name: helixterminator
  namespace: helixterminator
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 128Gi
    limits.cpu: "200"
    limits.memory: 256Gi
    pods: "200"
    services: "100"
    persistentvolumeclaims: "50"
    secrets: "100"
    configmaps: "100"
